fun callFail(p: String?) {
    val s = p ?: throw Exception("message")
    println(s)
}
